import Head from 'next/head'
import { useState, useEffect } from "react";
import Cookie from "js-cookie";
import { parseCookies } from "../lib/parseCookies";


const Index = ({ initialRememberValue = "sdfgsdfg" }) => {
  const [username, setUsername] = useState("");

function updateCookie() {
  Cookie.set("username", username);
}

  return (
    <div>
      <Head>
        <title>Sevda and Craig Cookies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form>
          username
          <input
            type="text"
            name="usernameInput"
            onKeyUp={e => setUsername(e.target.value)}
          />
          <button type="submit" onClick={() => updateCookie()}>submit</button>
        </form>
      </div>
    </div>
  )
}

Index.getInitialProps = ({ req }) => {
  const cookies = parseCookies(req);

  return {
    initialRememberValue: cookies.rememberMe
  };
};

export default Index;