import Layout from "../components/Layout";
import { useState } from "react";
import Cookie from "js-cookie";
import { parseCookies } from "../lib/parseCookies";
import Head from "next/head";

const Signup = () => {
  const [username, setUsername] = useState("");

  function updateCookie() {
    Cookie.set("username", username);
  }
  return (
    <Layout>
      <div>
        <Head>
          <title>Title</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <h1>Sign up</h1>
          <form action="" method="POST">
            <label htmlFor="name">
              Name
              <span aria-hidden="true">*</span>
            </label>
            <input
              id="name"
              name="name"
              type="text"
              required
              onKeyUp={(e) => setUsername(e.target.value)}
            />
            <label htmlFor="email">
              Email address
              <span aria-hidden="true">*</span>
            </label>
            <input id="email" name="email" type="email" required />
            <label htmlFor="password">
              Password
              <span aria-hidden="true">*</span>
            </label>
            <input
              id="password"
              name="password"
              type="password"
              aria-describedby="passwordRequirements"
              required
            />
            {/* Test*/}
            <label htmlFor="password">
              Gender
              <span aria-hidden="true">*</span>
            </label>
            <input
              id="gender"
              name="gender"
              type="gender"
              aria-describedby="genderedRequirements"
              required
            />

            <label htmlFor="password">
              Gender
              <span aria-hidden="true">*</span>
            </label>
            <input
              id="gender"
              name="gender"
              type="gender"
              aria-describedby="genderedRequirements"
              required
            />

            <label htmlFor="imageUrl">
              Image Url
              <span aria-hidden="true">*</span>
            </label>
            <input
              id="imageUrl"
              name="imageUrl"
              type="imageUrl"
              aria-describedby="imageUrlRequirements"
              required
            />

            <button type="submit" onClick={() => updateCookie()}>
              submit
            </button>
          </form>
        </div>
      </div>
    </Layout>
  );
};

Signup.getInitialProps = ({ req }) => {
  const cookies = parseCookies(req);

  return {
    initialRememberValue: cookies.rememberMe,
  };
};
// Signup.getInitialProps = ({ req }) => {
//   const cookies = parseCookies(req);

export default Signup;
